// MARK: - GeneratedCard

/// A single platform card generated by the content AI.
///
/// Each `GeneratedCard` corresponds to one social platform (e.g. `"reel"`, `"blog_post"`)
/// and carries all the data needed to create or update a Trello card via
/// `TrelloAPIClient.createCard(_:)`.
///
/// `CodingKeys` map Swift camelCase to the AI's snake_case JSON keys.
public struct GeneratedCard: Codable {
    /// Canonical platform key (e.g. `"reel"`, `"blog_post"`).
    public let platform: String
    /// Emoji-prefixed display label (e.g. `"🎬 Reel"`).
    public let platformLabel: String
    /// Trello card title with date placeholder (e.g. `"🎬 Reel | 2026 DD MMMM | HH:MM | cancun_v01"`).
    public let trelloTitle: String
    /// Output filename for this platform.
    public let archivoFinal: String
    /// Published URL of the web article.
    ///
    /// Optional in the JSON schema — the field may be absent when the AI doesn't
    /// know the URL yet.  Decoded with `decodeIfPresent`; defaults to `""`.
    public let blogUrl: String
    /// Content title for this platform.
    public let titulo: String
    /// Full content description / copy for this platform.
    public let descripcion: String
    /// Platform-appropriate hashtags.
    public let hashtags: [String]
    /// Short one-line summary of the description.
    public let resumenDescripcion: String
    /// Ready-to-paste prompt for an image AI (DALL-E, Midjourney, etc.).
    ///
    /// Present only when the source request carries an "imagen" label in Trello.
    /// When non-nil, Step 2 saves the card to the local `ImageBucketStore` and
    /// adds a `[IMAGE_BACKUP]` recovery comment to the Trello card.
    public let imagePrompt: String?
    /// Image format hint: `"story"` (9:16 vertical) or `"post"` (1:1 / 4:5).
    /// Derived from `platform` — `instagram_story` → story, `instagram_post` → post.
    public let imageFormat: String?
    /// Number of image pieces needed for this card (1–4).
    /// 1 = single image; 2–4 = sequence / carousel.
    public let numeroPiezas: Int?
    /// Trello card ID of the original OUTPUT card to move when processing
    /// image-only requests (`platform == "imagen"`).
    ///
    /// The AI echoes back this ID so Step 2 can locate and move the
    /// source card without creating a duplicate.
    public let originalCardId: String?

    enum CodingKeys: String, CodingKey {
        case platform
        case platformLabel      = "platform_label"
        case trelloTitle        = "trello_title"
        case archivoFinal       = "archivo_final"
        case blogUrl            = "blog_url"
        case titulo
        case descripcion
        case hashtags
        case resumenDescripcion = "resumen_descripcion"
        case imagePrompt        = "image_prompt"
        case imageFormat        = "image_format"
        case numeroPiezas       = "numero_piezas"
        case originalCardId     = "original_card_id"
    }

    // Custom decoder — all new fields are optional for backward compatibility.
    public init(from decoder: Decoder) throws {
        let c          = try decoder.container(keyedBy: CodingKeys.self)
        platform           = try c.decode(String.self,   forKey: .platform)
        platformLabel      = try c.decode(String.self,   forKey: .platformLabel)
        trelloTitle        = try c.decode(String.self,   forKey: .trelloTitle)
        archivoFinal       = try c.decode(String.self,   forKey: .archivoFinal)
        blogUrl            = try c.decodeIfPresent(String.self, forKey: .blogUrl) ?? ""
        titulo             = try c.decode(String.self,   forKey: .titulo)
        descripcion        = try c.decode(String.self,   forKey: .descripcion)
        hashtags           = try c.decode([String].self, forKey: .hashtags)
        resumenDescripcion = try c.decode(String.self,   forKey: .resumenDescripcion)
        imagePrompt        = try c.decodeIfPresent(String.self, forKey: .imagePrompt)
        imageFormat        = try c.decodeIfPresent(String.self, forKey: .imageFormat)
        numeroPiezas       = try c.decodeIfPresent(Int.self,    forKey: .numeroPiezas)
        originalCardId     = try c.decodeIfPresent(String.self, forKey: .originalCardId)
    }

    public init(
        platform: String,
        platformLabel: String,
        trelloTitle: String,
        archivoFinal: String,
        blogUrl: String = "",
        titulo: String,
        descripcion: String,
        hashtags: [String],
        resumenDescripcion: String,
        imagePrompt: String? = nil,
        imageFormat: String? = nil,
        numeroPiezas: Int? = nil,
        originalCardId: String? = nil
    ) {
        self.platform = platform
        self.platformLabel = platformLabel
        self.trelloTitle = trelloTitle
        self.archivoFinal = archivoFinal
        self.blogUrl = blogUrl
        self.titulo = titulo
        self.descripcion = descripcion
        self.hashtags = hashtags
        self.resumenDescripcion = resumenDescripcion
        self.imagePrompt = imagePrompt
        self.imageFormat = imageFormat
        self.numeroPiezas = numeroPiezas
        self.originalCardId = originalCardId
    }
}
