// MARK: - TrelloPromptOutput

/// The full output produced by the content-generation AI for a single request.
///
/// Matches the JSON schema defined in `ContentGenerationPromptFactory.scriptPrompt`.
/// `CodingKeys` map Swift camelCase to the AI's snake_case JSON keys.
public struct TrelloPromptOutput: Codable {
    /// Snake_case content identifier generated by the AI (e.g. `"cancun_primer_dia"`).
    public let id: String
    /// Base filename for the generated content files.
    public let archivoFinal: String
    /// Visual strategy description.
    public let estrategiaVisual: String
    /// Thumbnail metadata for video platforms.
    public let miniatura: Miniature
    /// On-screen text suggestions for video overlays.
    public let textoEnPantalla: [String]
    /// Main hook phrase for the content.
    public let hookPrincipal: String
    /// Call-to-action copy.
    public let cta: String
    /// Per-platform generated cards.
    public let cards: [GeneratedCard]

    enum CodingKeys: String, CodingKey {
        case id
        case archivoFinal       = "archivo_final"
        case estrategiaVisual   = "estrategia_visual"
        case miniatura
        case textoEnPantalla    = "texto_en_pantalla"
        case hookPrincipal      = "hook_principal"
        case cta
        case cards
    }

    public init(
        id: String,
        archivoFinal: String,
        estrategiaVisual: String,
        miniatura: Miniature,
        textoEnPantalla: [String],
        hookPrincipal: String,
        cta: String,
        cards: [GeneratedCard]
    ) {
        self.id = id
        self.archivoFinal = archivoFinal
        self.estrategiaVisual = estrategiaVisual
        self.miniatura = miniatura
        self.textoEnPantalla = textoEnPantalla
        self.hookPrincipal = hookPrincipal
        self.cta = cta
        self.cards = cards
    }
}

// MARK: - Miniature

/// Thumbnail metadata for video content.
///
/// Properties are intentionally in Spanish because they are domain data
/// sent to and returned by the AI.
public struct Miniature: Codable {
    public let nombre: String
    public let texto: String
    public let estilo: String

    public init(nombre: String, texto: String, estilo: String) {
        self.nombre = nombre
        self.texto = texto
        self.estilo = estilo
    }
}

// MARK: - BatchPromptOutput

/// Wraps multiple `TrelloPromptOutput` items returned by the AI in batch mode.
public struct BatchPromptOutput: Codable {
    /// One output per request, in the same order as the batch input.
    public let outputs: [TrelloPromptOutput]

    public init(outputs: [TrelloPromptOutput]) {
        self.outputs = outputs
    }
}

// MARK: - YouTubePromptOutput

/// Output produced by the YouTube Ultra Pro AI prompt for a long-form video.
///
/// Contains:
/// - `youtubeAssets`: full Markdown of FASE 0 + FASE 1 — saved to `LocalState/youtube/`
/// - `cards`: exactly 6 grouped `GeneratedCard` entries.
///
/// The workflow later collapses those 6 grouped sections into:
/// - 1 Trello master card (`youtube_video`)
/// - 5 Trello comments attached to that card
///
/// `CodingKeys` map Swift camelCase to the AI's snake_case JSON keys.
public struct YouTubePromptOutput: Codable {
    /// Video identifier in snake_case (e.g. `"dtav_japon_travel01"`).
    public let id: String
    /// Base filename — also used as the master file name on disk (e.g. `"DTAV_CDMX_v01"`).
    public let archivoBase: String
    /// Best SEO+CTR optimized title for the video.
    ///
    /// Optional in the JSON schema — defaults to `""` when absent so old responses
    /// still parse correctly. The pipeline falls back to `youtube_produccion.titulo`.
    public let tituloOptimizado: String
    /// Complete Markdown output of FASE 0 + FASE 1 — stored verbatim as a backup.
    ///
    /// The master file is built from `cards[].descripcion` (more reliable) but
    /// `youtubeAssets` is appended when non-empty so nothing is lost.
    public let youtubeAssets: String
    /// Six grouped sections extracted from the full prompt output:
    ///
    /// 1. `youtube_grabacion`      — FASE 0 completa (guion, plan, locaciones, shot list)
    /// 2. `youtube_produccion`     — Resumen · Hook · Viralidad · Búsqueda · Títulos · Miniatura
    /// 3. `youtube_studio`         — Descripción YT · Capítulos · Tags · Keywords · Studio form
    /// 4. `youtube_comunidad_promo`— Post comunidad · IG · TikTok · Facebook · Twitter/X
    /// 5. `youtube_shorts_reels`   — Shorts · Reels · TikTok clips · Contenido derivado
    /// 6. `youtube_estrategia`     — Estrategia de publicación
    public let cards: [GeneratedCard]

    enum CodingKeys: String, CodingKey {
        case id
        case archivoBase       = "archivo_base"
        case tituloOptimizado  = "titulo_optimizado"
        case youtubeAssets     = "youtube_assets"
        case cards
    }

    // Custom decoder so `titulo_optimizado` and `youtube_assets` are optional.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id               = try c.decode(String.self,        forKey: .id)
        archivoBase      = try c.decode(String.self,        forKey: .archivoBase)
        tituloOptimizado = try c.decodeIfPresent(String.self, forKey: .tituloOptimizado) ?? ""
        youtubeAssets    = try c.decodeIfPresent(String.self, forKey: .youtubeAssets)    ?? ""
        cards            = try c.decode([GeneratedCard].self, forKey: .cards)
    }

    public init(id: String, archivoBase: String, tituloOptimizado: String = "",
                youtubeAssets: String = "", cards: [GeneratedCard]) {
        self.id = id
        self.archivoBase = archivoBase
        self.tituloOptimizado = tituloOptimizado
        self.youtubeAssets = youtubeAssets
        self.cards = cards
    }
}
